### ISSUE TITLE
Up/Down room collisions

### ISSUE THREAD

**Issue by daagar** [Chris7/3k-Scripts#5]
The mapper does a good job at handling conflicts in x,y coordinate space by making conflicting rooms 1/2 the distance. However, because up/down rooms aren't spread out in this way, conflicts aren't being detected and you end up stomping on rooms. 

A real simple example: 
- Start mapping from Center of Town.
- Go one west, down, down, south.
- Head back partially by going north, up. 
- Head south. Note that this room has a 'down' exit, but does _not_ lead to the room you just mapped previously.
- If you proceed to go down, it will stomp over the room that was there before. 

I have no suggestions on how to fix this off-hand. Spreading rooms out in the z plane would work, of course, but that would be pretty ugly and non-intuitive. A short-term solution might be to just throw up an error that a conflicting room was detected, and prevent the room from being created and leave it to the user to move the room out of the way manually.

**Comment by Chris7** [comment]
hmm, this one is going to be tricky. one approach is to search for a hole,
put the room there and throw an error to warn the user in case they want to
move it.  i like that better than the no map + manual move because they
have to manually move it maybe in this instance.  I'll play around with it.

sent from my phone
On Aug 3, 2012 5:05 PM, "daagar" <
reply@reply.github.com>
wrote:

**Comment by daagar** [comment]
Searching for a hole would fail though (or be obnoxious) if the area below was some huge grid. One option would be to shove all the layers down by a z-level. So if there is a conflict between level 0 and level -1, you move all rooms on level -1 to -2, all rooms on -2 to -3, etc., and then create the new room on -1.

**Comment by Chris7** [comment]
After a long wait, this is in.
